# Workflow of filtering marker selection table generated by marker selection function ####
library(Seurat)
library(dplyr)
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(data.table)

# Set working directory ####
wd = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter"
setwd(wd)
rawdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata/patient_hlcma"

outdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_addsplits/patient_hlcma_addsplits/hlcma0001/3groups_level2"

# filter #####
## Tumor_Vs_Alveolar ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Alveolar_background.rds"))
    if(!is.null(marker_gene_table)){
      marker_gene_table$sample_type <- sample_type[k]
      subset_marker_gene1 <- marker_gene_table %>%
        filter(marker_gene_table$avg_log2FC<0 )
      
      subset_marker_gene2 <- marker_gene_table %>%
        filter(marker_gene_table$avg_log2FC>0,avg.exp >5 )
      
      subset_marker_gene <- rbind(subset_marker_gene1,subset_marker_gene2)
    }
    saveRDS(subset_marker_gene,paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Alveolar_background_filter.rds"))
    
  }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Alveolar_background.rds"))
    marker_gene_table2$sample_type <- sample_type[k]
    subset_marker_gene1 <- marker_gene_table2 %>%
      filter(marker_gene_table2$avg_log2FC<0 )
    
    subset_marker_gene2 <- marker_gene_table2 %>%
      filter(marker_gene_table2$avg_log2FC>0,avg.exp >5 )
    
    marker_gene_table2 <- rbind(subset_marker_gene1,subset_marker_gene2)
    saveRDS(marker_gene_table2,paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Alveolar_background_filter.rds"))
    
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
  
  write.csv(marker_gene_table,paste0(outdir,"/add_background/level2_Tumor_Vs_Alveolar_marker_selection_table_expression_filter.csv"),row.names = F)
  
}  

## Tumor_Vs_Airway ####
#no luadc tumor vs airway markers
k <- 1L
for(k in 1:2){ 
  
  print(sample_type[k])
  
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Airway_background.rds"))
    if(!is.null(marker_gene_table)){
      marker_gene_table$sample_type <- sample_type[k]
      subset_marker_gene1 <- marker_gene_table %>%
        filter(marker_gene_table$avg_log2FC<0 )
      
      subset_marker_gene2 <- marker_gene_table %>%
        filter(marker_gene_table$avg_log2FC>0,avg.exp >5 )
      
      subset_marker_gene <- rbind(subset_marker_gene1,subset_marker_gene2)
    }
    saveRDS(subset_marker_gene,paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Airway_background_filter.rds"))
    
  }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Airway_background.rds"))
    marker_gene_table2$sample_type <- sample_type[k]
    subset_marker_gene1 <- marker_gene_table2 %>%
      filter(marker_gene_table2$avg_log2FC<0 )
    
    subset_marker_gene2 <- marker_gene_table2 %>%
      filter(marker_gene_table2$avg_log2FC>0,avg.exp >5 )
    
    marker_gene_table2 <- rbind(subset_marker_gene1,subset_marker_gene2)
    saveRDS(marker_gene_table2,paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Airway_background_filter.rds"))
    
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
  
  write.csv(marker_gene_table,paste0(outdir,"/add_background/level2_Tumor_Vs_Airway_marker_selection_table_expression_filter.csv"),row.names = F)
  
}  


# non-filter #####
## Tumor_Vs_Alveolar ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Alveolar_background.rds"))
    if(!is.null(marker_gene_table)){
      marker_gene_table$sample_type <- sample_type[k]
     
    }
   
  }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Alveolar_background.rds"))
    marker_gene_table2$sample_type <- sample_type[k]
    
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
  
  write.csv(marker_gene_table,paste0(outdir,"/add_background/level2_Tumor_Vs_Alveolar_marker_selection_table_expression.csv"),row.names = F)
  
}  

## Tumor_Vs_Airway ####
#no luadc tumor vs airway markers
k <- 1L
for(k in 1:2){ 
  
  print(sample_type[k])
  
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Airway_background.rds"))
    if(!is.null(marker_gene_table)){
      marker_gene_table$sample_type <- sample_type[k]
     
    }
    
  }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/add_background/",sample_type[k],"_marker_gene_table_Tumor_Vs_Airway_background.rds"))
    marker_gene_table2$sample_type <- sample_type[k]
    
    
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
  
  write.csv(marker_gene_table,paste0(outdir,"/add_background/level2_Tumor_Vs_Airway_marker_selection_table_expression.csv"),row.names = F)
  
}  

