# Workflow of filtering marker selection table generated by marker selection function ####
library(Seurat)
library(dplyr)
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(data.table)

# Set working directory ####
wd = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter"
setwd(wd)
rawdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata/patient_hlcma"

outdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_addsplits/patient_hlcma_addsplits"


# Read files ####
ob <- readRDS(paste0("/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata/patient_hlcma/patient_hlcma_tumor_added_addsplits_fixedAnno.rds"))
sampledata <- ob@meta.data

sample_type <- unique(sort(sampledata$disease))

ob_split <- SplitObject(ob, split.by = "disease")
#for the integrated object with tumor annotation, only the new surface markers version was done
  
# new marker list (surfaceGenie) ####
## non-stratified cells ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  ob_split2 <- ob_split[[sample_type[k]]]
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/old/",sample_type[k],"_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
    # step 0: filter for FDR < 2 (to collect almost all)
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<2)
    
    
    if(T){
      # step 0: filter for expression level
      features <- unique(sort(marker_gene_table$gene))
      d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
      exp_data <- d[["data"]]
      exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
      exp_data <- exp_data[,c(1,2,5,6)]
      marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
      marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
      marker_gene_table$backgroud_exp <- marker_gene_table$avg.exp/(2^(marker_gene_table$avg_log2FC))
      #marker_gene_table <- marker_gene_table %>%
      #  filter(marker_gene_table$backgroud_exp <0.8) 
    }
    marker_gene_table <- marker_gene_table %>% 
      arrange(annotation.l2,p_val)
    marker_gene_table$mergeID <- NULL
    
    subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
    # step 0: filter for non-HLA
    subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
   # subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
    print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
}  

## level2 ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  ob_split2 <- ob_split[[sample_type[k]]]
  ob_split3 <- SplitObject(ob_split2, split.by = "split1")
  ob_split3 = ob_split3$`PTPRC-`
  ob_split4 <- SplitObject(ob_split3, split.by = "split2")
  ob_split4 = ob_split4$`EPCAM+`
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/level2_marker_selection_table/old/",sample_type[k],"_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
    # step 0: filter for FDR < 2 (to collect almost all)
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<2)
    
    
    if(T){
      # step 0: filter for expression level
      features <- unique(sort(marker_gene_table$gene))
      d <- DotPlot(ob_split4, features = features, group.by = "annotation.l2") + RotatedAxis()
      exp_data <- d[["data"]]
      exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
      exp_data <- exp_data[,c(1,2,5,6)]
      marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
      marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
      marker_gene_table$backgroud_exp <- marker_gene_table$avg.exp/(2^marker_gene_table$avg_log2FC)
     # marker_gene_table <- marker_gene_table %>%
    #    filter(marker_gene_table$backgroud_exp <0.8) 
    }
    marker_gene_table <- marker_gene_table %>% 
      arrange(annotation.l2,p_val)
    marker_gene_table$mergeID <- NULL
    
    subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
    # step 0: filter for non-HLA
    subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
    #subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
    print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/level2_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
}  

## CD45- ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  ob_split2 <- ob_split[[sample_type[k]]]
  ob_split3 <- SplitObject(ob_split2, split.by = "split1")
  ob_split3 = ob_split3$`PTPRC-`
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/CD45-_marker_selection_table/old/",sample_type[k],"_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
    # step 0: filter for FDR < 2 (to collect almost all)
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<2)
    
    
    if(T){
      # step 0: filter for expression level
      features <- unique(sort(marker_gene_table$gene))
      d <- DotPlot(ob_split3, features = features, group.by = "annotation.l2") + RotatedAxis()
      exp_data <- d[["data"]]
      exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
      exp_data <- exp_data[,c(1,2,5,6)]
      marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
      marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
      marker_gene_table$backgroud_exp <- marker_gene_table$avg.exp/(2^marker_gene_table$avg_log2FC)
      #marker_gene_table <- marker_gene_table %>%
      #  filter(marker_gene_table$backgroud_exp <0.8) 
    }
    marker_gene_table <- marker_gene_table %>% 
      arrange(annotation.l2,p_val)
    marker_gene_table$mergeID <- NULL
    
    subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
    # step 0: filter for non-HLA
    subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
    #subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
    print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/CD45-_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
}  

# save CSV #####
## non-stratified cells ####
k <- 2L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
 
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
    marker_gene_table$sample_type <- sample_type[k]
    }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
    marker_gene_table2$sample_type <- sample_type[k]
    
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
 
  write.csv(marker_gene_table,paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/add_background/non_stratified_marker_slection_table_expression_added.csv"),row.names = F)
  
}  

## level2 ####
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/level2_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
    marker_gene_table$sample_type <- sample_type[k]
  }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/hlcma0001/level2_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
    marker_gene_table2$sample_type <- sample_type[k]
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
  
  write.csv(marker_gene_table,paste0(outdir,"/hlcma0001/level2_marker_selection_table/add_background/level2_marker_slection_table_expression_added.csv"),row.names = F)
  
}  


## CD45- ####
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
 
  if(k==1){
    marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/CD45-_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
    marker_gene_table$sample_type <- sample_type[k]
    
  }else{
    marker_gene_table2 <- readRDS(paste0(outdir,"/hlcma0001/CD45-_marker_selection_table/add_background/",sample_type[k],"_table_add_background.rds"))
   
    marker_gene_table2$sample_type <- sample_type[k]
    print(dim(marker_gene_table2))
    
    marker_gene_table <- rbind(marker_gene_table,marker_gene_table2)
    
    print(dim(marker_gene_table))
  }
  
  write.csv(marker_gene_table,paste0(outdir,"/hlcma0001/CD45-_marker_selection_table/add_background/CD45-_marker_slection_table_expression_added.csv"),row.names = F)
  
}  
