# Workflow of filtering marker selection table generated by marker selection function ####
library(Seurat)
library(dplyr)
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(data.table)

# Set working directory ####
wd = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter"
setwd(wd)
rawdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata/patient_hlcma"

outdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_addsplits/patient_hlcma_addsplits"

# Load functions



# Read files ####


sample_type <- c("distal_normal","luadc","tan")

# old surface markers (GO) ####

## non-stratified cells ####
k <- 1L
for(k in 1:length(sample_type)){ 

 print(sample_type[k])
 
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/old/",sample_type[k],"_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
  # step 0: filter for FDR < 1 (to collect almost all)
  marker_gene_table <- marker_gene_table %>%
    filter(marker_gene_table$p_val_adj<1)
  
  
  if(F){
  # step 0: filter for expression level
  features <- unique(sort(marker_gene_table$gene))
  d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
  exp_data <- d[["data"]]
  exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
  exp_data <- exp_data[,c(1,2,5,6)]
  marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
  marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
  }
  
  if(F){
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$avg.exp >1) 
  }
  marker_gene_table <- marker_gene_table %>% 
    arrange(annotation.l2,p_val)
  marker_gene_table$mergeID <- NULL

  subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
  # step 0: filter for non-HLA
  subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
  subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
  print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/",sample_type[k],"_marker_gene_table_subset_arranged.rds"))
}  

## level2 ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/level2_marker_selection_table/old/",sample_type[k],"_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
    # step 0: filter for FDR < 1 (to collect almost all)
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<1)
    
    
    if(F){
      # step 0: filter for expression level
      features <- unique(sort(marker_gene_table$gene))
      d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
      exp_data <- d[["data"]]
      exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
      exp_data <- exp_data[,c(1,2,5,6)]
      marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
      marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
    }
    
    if(F){
      marker_gene_table <- marker_gene_table %>%
        filter(marker_gene_table$avg.exp >1) 
    }
    marker_gene_table <- marker_gene_table %>% 
      arrange(annotation.l2,p_val)
    marker_gene_table$mergeID <- NULL
    
    subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
    # step 0: filter for non-HLA
    subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
    subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
    print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/level2_marker_selection_table/",sample_type[k],"_SurfaceGenie_marker_gene_table_subset_arranged.rds"))
}  




# new marker list (surfaceGenie) ####
## non-stratified cells ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/old/",sample_type[k],"_SurfaceGenie_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
    # step 0: filter for FDR < 1 (to collect almost all)
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<1)
    
    
    if(F){
      # step 0: filter for expression level
      features <- unique(sort(marker_gene_table$gene))
      d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
      exp_data <- d[["data"]]
      exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
      exp_data <- exp_data[,c(1,2,5,6)]
      marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
      marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
    }
    
    if(F){
      marker_gene_table <- marker_gene_table %>%
        filter(marker_gene_table$avg.exp >1) 
    }
    marker_gene_table <- marker_gene_table %>% 
      arrange(annotation.l2,p_val)
    marker_gene_table$mergeID <- NULL
    
    subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
    # step 0: filter for non-HLA
    subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
    subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
    print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/non_stratify_marker_selection_table/",sample_type[k],"_SurfaceGenie_marker_gene_table_subset_arranged.rds"))
}  

## level2 ####
k <- 1L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  marker_gene_table <- readRDS(paste0(outdir,"/hlcma0001/level2_marker_selection_table/old/",sample_type[k],"_SurfaceGenie_marker_gene_table_all.rds"))
  print(dim(marker_gene_table))
  if(!is.null(marker_gene_table)){
    # step 0: filter for FDR < 1 (to collect almost all)
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<1)
    
    
    if(F){
      # step 0: filter for expression level
      features <- unique(sort(marker_gene_table$gene))
      d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
      exp_data <- d[["data"]]
      exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
      exp_data <- exp_data[,c(1,2,5,6)]
      marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
      marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
    }
    
    if(F){
      marker_gene_table <- marker_gene_table %>%
        filter(marker_gene_table$avg.exp >1) 
    }
    marker_gene_table <- marker_gene_table %>% 
      arrange(annotation.l2,p_val)
    marker_gene_table$mergeID <- NULL
    
    subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
    # step 0: filter for non-HLA
    subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
    subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
    print(dim(subset_marker_gene))
  }
  saveRDS(subset_marker_gene,paste0(outdir,"/hlcma0001/level2_marker_selection_table/",sample_type[k],"_SurfaceGenie_marker_gene_table_subset_arranged.rds"))
}  
