# Workflow of filtering marker selection table generated by marker selection function ####
library(Seurat)
library(dplyr)
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(data.table)

# Set working directory ####
wd = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter"
setwd(wd)
rawdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_each_dataset"
outdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_addsplits/lung_mapped_cellxgene_fixed_addsplits"

# Load functions
GetfileNames <- function(fileDir, pattern = ".rds"){
  filenames <- list.files(fileDir, pattern= pattern, full.names=TRUE)
  filename <- sub(paste0(".*",fileDir,"/"), "", filenames)
  filename <- sub(pattern, "", filename)  
  return(filename)
}


# Read files ####
#ReadRDSFiles(rawdir, envir = .GlobalEnv)
filename <- GetfileNames(rawdir, pattern = ".rds")

sample_type <- readRDS("/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata/LIST_lung_seuratsplit_7datasets_samples_disease.rds")

# new marker list (surfaceGenie) ####
## non-stratified cells ####
#i <- 1L
for(i in 1: length(filename)){ 
  print(filename[i])
  disease <- sample_type[[filename[i]]]
  print(disease)
  #k <- 1L
  for(k in 1:length(disease)){ 
    
    print(disease[k])
    #ob_split2 = ob_split[[split[k]]]
    marker_gene_table <- readRDS(paste0(outdir,"/",filename[i],"/old_marker_selection_table/",disease[k],"_SurfaceGenie_marker_gene_table_all.rds"))
    print(dim(marker_gene_table))
    if(!is.null(marker_gene_table)){
      # step 0: filter for FDR < 1 (to collect almost all)
      marker_gene_table <- marker_gene_table %>%
        filter(marker_gene_table$p_val_adj<1)
      
      
      if(F){
        features <- unique(sort(marker_gene_table$gene))
        d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
        exp_data <- d[["data"]]
        exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
        exp_data <- exp_data[,c(1,2,5,6)]
        marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
        marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
      }
      
      if(F){
        marker_gene_table <- marker_gene_table %>%
          filter(marker_gene_table$avg.exp >1) 
      }
      marker_gene_table <- marker_gene_table %>% 
        arrange(annotation.l2,p_val)
      marker_gene_table$mergeID <- NULL
      
      subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
      subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
      subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
      print(dim(subset_marker_gene))
    }
    saveRDS(subset_marker_gene,paste0(outdir,"/",filename[i],"/",disease[k],"_SurfaceGenie_marker_gene_table_subset_arranged.rds"))
  }  
  
}

## level2 ####
for(i in 1: length(filename)){ 
  print(filename[i])
  disease <- sample_type[[filename[i]]]
  print(disease)
  #k <- 1L
  for(k in 1:length(disease)){ 
    
    print(disease[k])
    #ob_split2 = ob_split[[split[k]]]
    marker_gene_table <- readRDS(paste0(outdir,"/",filename[i],"/level2_marker_selection_table/",disease[k],"_SurfaceGenie_marker_gene_table_all.rds"))
    print(dim(marker_gene_table))
    if(!is.null(marker_gene_table)){
      # step 0: filter for FDR < 1 (to collect almost all)
      marker_gene_table <- marker_gene_table %>%
        filter(marker_gene_table$p_val_adj<1)
      
      
      if(F){
        features <- unique(sort(marker_gene_table$gene))
        d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
        exp_data <- d[["data"]]
        exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
        exp_data <- exp_data[,c(1,2,5,6)]
        marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
        marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
      }
      
      if(F){
        marker_gene_table <- marker_gene_table %>%
          filter(marker_gene_table$avg.exp >1) 
      }
      marker_gene_table <- marker_gene_table %>% 
        arrange(annotation.l2,p_val)
      marker_gene_table$mergeID <- NULL
      
      subset_marker_gene <- data.table(marker_gene_table, key="annotation.l2") 
      subset_marker_gene = subset_marker_gene[!grepl("HLA",subset_marker_gene$gene),] 
      subset_marker_gene <- subset_marker_gene[, head(.SD, 100), by=annotation.l2] 
      print(dim(subset_marker_gene))
    }
    saveRDS(subset_marker_gene,paste0(outdir,"/",filename[i],"/Level2_",disease[k],"_SurfaceGenie_marker_gene_table_subset_arranged.rds"))
  }  
  
}
