# Workflow of filtering marker selection table generated by marker selection function ####
library(Seurat)
library(dplyr)
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(data.table)

# Set working directory ####
wd = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter"
setwd(wd)
rawdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_each_dataset"
procdir= "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/rawdata_addsplits/lung_mapped_cellxgene_fixed_addsplits"
outdir = "/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/marker_selection_workflow/public/histogram_background_exp/"



# Read files ####

sample_type_all <- readRDS(paste0(procdir,"/list_sample_cohort.rds"))
sample_type <- c("adjacent_normal","luad","lusc")
cell.surface.marker <-readRDS("/omics/groups/OE0219/internal/Jessie_2021/P01.digital_sorter/SurfaceGenie/Union.cell.surface.marker.rds")

#for the integrated object with tumor annotation, only the new surface markers version was done


# new marker list (surfaceGenie) ####
## non-stratified cells ####
k <- 3L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  filename <- sample_type_all[[sample_type[k]]]
  
  
  f <- 1L
  for( f in 1: length(filename)){
    print(filename[f])
    marker_gene_table <- readRDS(paste0(procdir,"/",filename[f],"/old_marker_selection_table/",sample_type[k],"_SurfaceGenie_marker_gene_table_all.rds"))
    print(dim(marker_gene_table))
    # step 0: filter for FDR < 1 (to collect almost all) and cell surface marker gene
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<1)
    # add information for expression level
    features <- unique(sort(marker_gene_table$gene))
    
    ob <- readRDS(paste0(rawdir,"/",filename[f],".rds"))
    ob_split <- SplitObject(ob, split.by = "disease")
    
    ob_split2 <- ob_split[[sample_type[k]]]
    
    d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
    exp_data <- d[["data"]]
    exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
    exp_data <- exp_data[,c(1,2,5,6)]
    marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
    marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
    marker_gene_table$backgroud_exp <- marker_gene_table$avg.exp/(2^(marker_gene_table$avg_log2FC))
    marker_gene_table$cohort <-filename[f]
    if(f==1){
      combine_table <- marker_gene_table 
    }else{
      combine_table <- rbind(combine_table,marker_gene_table) 
      }
    }
  marker_gene_table1 <- combine_table %>%
    filter(combine_table$avg_log2FC > 0)# & marker_gene_table$backgroud_exp < 0.9)
  
  if(T){
    plot_data <- as.data.frame(marker_gene_table1$backgroud_exp)
    colnames(plot_data) <- "backgroud_exp"
    
    pdf(paste0(outdir,"non_stratify/",sample_type[k],"_backgroundExp_pos.pdf"), width = 8, height = 6)
    
    ggplot(plot_data , aes(x=backgroud_exp))+ 
      geom_histogram(binwidth=0.01,fill = "darkblue" ,colour='black',size=1)+
      xlim(NA, 1)+
      ggtitle(paste('non_stratify, + selected markers,',sample_type[k])) +
      xlab("Background expression") +
      ylab("Number of markers") +
      theme_classic()+
      theme(plot.title = element_text(size=20),
            axis.text.x = element_text(size = 16),
            axis.text.y = element_text(size = 16),
            axis.title=element_text(size=16))
    dev.off()
  }
  
  marker_gene_table2 <- combine_table %>%
    filter(combine_table$avg_log2FC < 0 )#& marker_gene_table$backgroud_exp > 3)
  
  if(T){
    plot_data <- as.data.frame(marker_gene_table2$backgroud_exp)
    colnames(plot_data) <- "backgroud_exp"
    
    pdf(paste0(outdir,"non_stratify/",sample_type[k],"_backgroundExp_neg_NOxlim.pdf"), width = 8, height = 6)
    
    ggplot(plot_data , aes(x=backgroud_exp))+ 
      geom_histogram(binwidth=1,fill = "darkblue" ,colour='black',size=1)+
      xlim(0, NA)+
      ggtitle(paste('non_stratify, - selected markers,',sample_type[k])) +
      xlab("Background expression") +
      ylab("Number of markers") +
      theme_classic()+
      theme(plot.title = element_text(size=20),
            axis.text.x = element_text(size = 16),
            axis.text.y = element_text(size = 16),
            axis.title=element_text(size=16))
    dev.off()
  }    
      
               
      
     
     
}
    
## level2 ####
k <- 3L
for(k in 1:length(sample_type)){ 
  
  print(sample_type[k])
  
  filename <- sample_type_all[[sample_type[k]]]
  
  
  f <- 3L
  for( f in 1: length(filename)){
    print(filename[f])
    marker_gene_table <- readRDS(paste0(procdir,"/",filename[f],"/level2_marker_selection_table/",sample_type[k],"_SurfaceGenie_marker_gene_table_all.rds"))
    print(dim(marker_gene_table))
    # step 0: filter for FDR < 1 (to collect almost all) and cell surface marker gene
    marker_gene_table <- marker_gene_table %>%
      filter(marker_gene_table$p_val_adj<1)
    # add information for expression level
    features <- unique(sort(marker_gene_table$gene))
    
    ob <- readRDS(paste0(rawdir,"/",filename[f],".rds"))
    ob_split <- SplitObject(ob, split.by = "disease")
    
    ob_split2 <- ob_split[[sample_type[k]]]
    
    d <- DotPlot(ob_split2, features = features, group.by = "annotation.l2") + RotatedAxis()
    exp_data <- d[["data"]]
    exp_data$mergeID <- paste(exp_data$features.plot,exp_data$id)
    exp_data <- exp_data[,c(1,2,5,6)]
    marker_gene_table$mergeID <- paste(marker_gene_table$gene, marker_gene_table$annotation.l2)
    marker_gene_table <- merge(marker_gene_table, exp_data, by = "mergeID")
    marker_gene_table$backgroud_exp <- marker_gene_table$avg.exp/(2^(marker_gene_table$avg_log2FC))
    marker_gene_table$cohort <-filename[f]
    if(f==1){
      combine_table <- marker_gene_table 
    }else{
      combine_table <- rbind(combine_table,marker_gene_table) 
    }
  }
  marker_gene_table1 <- combine_table %>%
    filter(combine_table$avg_log2FC > 0)# & marker_gene_table$backgroud_exp < 0.9)
  
  if(T){
    plot_data <- as.data.frame(marker_gene_table1$backgroud_exp)
    colnames(plot_data) <- "backgroud_exp"
    
    pdf(paste0(outdir,"level2/",sample_type[k],"_backgroundExp_pos.pdf"), width = 8, height = 6)
    
    ggplot(plot_data , aes(x=backgroud_exp))+ 
      geom_histogram(binwidth=0.01,fill = "darkblue" ,colour='black',size=1)+
      xlim(NA, 1)+
      ggtitle(paste('level2, + selected markers,',sample_type[k])) +
      xlab("Background expression") +
      ylab("Number of markers") +
      theme_classic()+
      theme(plot.title = element_text(size=20),
            axis.text.x = element_text(size = 16),
            axis.text.y = element_text(size = 16),
            axis.title=element_text(size=16))
    dev.off()
  }
  
  marker_gene_table2 <- combine_table %>%
    filter(combine_table$avg_log2FC < 0 )#& marker_gene_table$backgroud_exp > 3)
  
  if(T){
    plot_data <- as.data.frame(marker_gene_table2$backgroud_exp)
    colnames(plot_data) <- "backgroud_exp"
    
    pdf(paste0(outdir,"level2/",sample_type[k],"_backgroundExp_neg.pdf"), width = 8, height = 6)
    
    ggplot(plot_data , aes(x=backgroud_exp))+ 
      geom_histogram(binwidth=1,fill = "darkblue" ,colour='black',size=1)+
      xlim(0, 20)+
      ggtitle(paste('level2, - selected markers,',sample_type[k])) +
      xlab("Background expression") +
      ylab("Number of markers") +
      theme_classic()+
      theme(plot.title = element_text(size=20),
            axis.text.x = element_text(size = 16),
            axis.text.y = element_text(size = 16),
            axis.title=element_text(size=16))
    dev.off()
  }    
  
  
  
  
  
}

## CD45- ####
